//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHoaDonBH
    {
        public string MaHD { get; set; }
        public string MaSP { get; set; }
        public string DVT { get; set; }
        public decimal SoLuong { get; set; }
        public decimal DonGia { get; set; }
        public decimal ChietKhau { get; set; }
        public decimal ThanhTien { get; set; }
        public Nullable<decimal> GiaMua { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public Nullable<decimal> LoiNhuan { get; set; }
    
        public virtual HoaDonBH HoaDonBH { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
