//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonBH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonBH()
        {
            this.CTHoaDonBH = new HashSet<CTHoaDonBH>();
        }
    
        public string MaHD { get; set; }
        public string MaKH { get; set; }
        public int MANV { get; set; }
        public int UserID { get; set; }
        public System.DateTime NgayBan { get; set; }
        public decimal TangThem { get; set; }
        public decimal TongThu { get; set; }
        public decimal DaThanhToan { get; set; }
        public decimal CongNo { get; set; }
        public decimal LoiNhuanHD { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaBan { get; set; }
        public string MaKM { get; set; }
        public int TrangThaiPhaChe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonBH> CTHoaDonBH { get; set; }
        public virtual plp_Ban plp_Ban { get; set; }
        public virtual plp_KhuyenMai plp_KhuyenMai { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual plp_LoginUser plp_LoginUser { get; set; }
    }
}
