//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.HoaDonBH = new HashSet<HoaDonBH>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public string TenCuaHang { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public int MaKV { get; set; }
        public int MaNhomKH { get; set; }
        public Nullable<int> MaHang { get; set; }
        public int DiemTichLuy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBH> HoaDonBH { get; set; }
        public virtual plp_HangThanhVien plp_HangThanhVien { get; set; }
        public virtual plp_KhuVuc plp_KhuVuc { get; set; }
        public virtual plp_NhomKH plp_NhomKH { get; set; }
    }
}
