//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plp_Ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plp_Ban()
        {
            this.HoaDonBH = new HashSet<HoaDonBH>();
        }
    
        public int MaBan { get; set; }
        public string TenBan { get; set; }
        public int MaKhuVuc { get; set; }
        public Nullable<int> SoGhe { get; set; }
        public int TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBH> HoaDonBH { get; set; }
        public virtual plp_KhuVuc_Ban plp_KhuVuc_Ban { get; set; }
    }
}
