//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plp_KhuVuc_Ban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plp_KhuVuc_Ban()
        {
            this.plp_Ban = new HashSet<plp_Ban>();
        }
    
        public int MaKhuVuc { get; set; }
        public string TenKhuVuc { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plp_Ban> plp_Ban { get; set; }
    }
}
