//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plp_LoginUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plp_LoginUser()
        {
            this.HoaDonBH = new HashSet<HoaDonBH>();
        }
    
        public int UserID { get; set; }
        public string Login_Name { get; set; }
        public string PW_matkhau { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDonBH> HoaDonBH { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
