//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace quanlycoffe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTHoaDonBH = new HashSet<CTHoaDonBH>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public int MaNCC { get; set; }
        public int MaDM { get; set; }
        public string MaSoRiengTA { get; set; }
        public string MaVach { get; set; }
        public string DVT { get; set; }
        public string DVT_QC { get; set; }
        public int QuyCach { get; set; }
        public decimal GiaMua { get; set; }
        public decimal GiaBan { get; set; }
        public decimal SoLuongTrongKho { get; set; }
        public decimal ChietKhau { get; set; }
        public string TenBietDuoc { get; set; }
        public Nullable<System.DateTime> HanDung { get; set; }
        public bool HetHang { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHoaDonBH> CTHoaDonBH { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
